# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a78bcab95fa9872cbbba0bfa83e2d77e9f40ba267ed1ec0f2b8019619f76189730d5481747b471a03641b1790f05d474ba5f2bd99f831a75c56eaf57f81b74

test:
  secret_key_base: 643bbae13b9225f6a29603f0b62906a2f0ba277320f1b92abb2078ebff426a90c0c22d05530240c16c67494020013f5f2288451d1f6284197231784e9564419e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
